pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:24.0.5
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
'''
        }
    }

    environment {
        DOCKER_IMAGE = "oithreed/brainwalk-frontend"
        DOCKER_CREDENTIALS_ID = "dockerhub-credentials"
    }

    stages {
        stage('Set Image Tag') {
            steps {
                script {
                    env.IMAGE_TAG = "${BUILD_NUMBER}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                container('docker') {
                    sh 'cd DUNOESANCHAEG-Client && docker build -t $DOCKER_IMAGE:$IMAGE_TAG -t $DOCKER_IMAGE:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(
                        credentialsId: DOCKER_CREDENTIALS_ID,
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )]) {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                        sh 'docker push $DOCKER_IMAGE:$IMAGE_TAG'
                        sh 'docker push $DOCKER_IMAGE:latest'
                    }
                }
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-access',
                        usernameVariable: 'GITHUB_USERNAME',
                        passwordVariable: 'GITHUB_TOKEN'
                    )]) {
                        sh """
                        apk add --no-cache git
                        rm -rf brainwalk-k8s-manifests

                        git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/0lthree/brainwalk-k8s-manifests.git
                        cd brainwalk-k8s-manifests/frontend

                        sed -i "s|image: .*|image: oithreed/brainwalk-frontend:${BUILD_NUMBER}|" deployment.yaml
                        
                        git config user.email "jenkins@brainwalk.com"
                        git config user.name "Jenkins"

                        git add .

                        git commit -m "Update frontend image to ${BUILD_NUMBER}" || echo "No changes"

                        git push
                        """
                    }
                }
            }
        }
    }
}

// Jenkins 자동 빌드 테스트를 위한 주석